# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='云厂商名称', max_length=50, verbose_name='云厂商名称')),
                ('code', models.CharField(help_text='云厂商代码', max_length=50, verbose_name='云厂商代码')),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.CharField(db_index=True, help_text='实例ID', max_length=100, verbose_name='实例ID')),
                ('instanceType', models.CharField(help_text='实例类型', max_length=100, verbose_name='实例类型')),
                ('instanceName', models.CharField(help_text='实例名', max_length=100, verbose_name='实例名')),
                ('cpu', models.CharField(help_text='cpu', max_length=100, verbose_name='cpu')),
                ('memory', models.CharField(help_text='memory', max_length=100, verbose_name='memory')),
                ('creationTime', models.DateTimeField(db_index=True, help_text='创建时间', verbose_name='创建时间')),
                ('expiredTime', models.DateTimeField(db_index=True, help_text='到期时间', verbose_name='到期时间')),
                ('startTime', models.DateTimeField(db_index=True, help_text='开始时间', verbose_name='开始时间')),
                ('hostName', models.CharField(db_index=True, help_text='主机名', max_length=100, verbose_name='主机名')),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Cloud')),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='inner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innerIpAddress', to='resources.Server'),
        ),
        migrations.AddField(
            model_name='ip',
            name='public',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicIpAddress', to='resources.Server'),
        ),
    ]
