

# aliyun key
ALI_ACCESS_KEY_ID = "LTAI54xDdOaCDtPY"
ALI_ACCESS_KEY_SECRET = "kEyAfgVosnru9Ynl0epJXpeyDBUGkw"
# QCLOUD key
QCLOUD_SECRETID = "AKIDFaq5EbGxiQx22qzUL2XtCJJ7j9NQuyTq"
QCLOUD_SECRETKEY = "LTP8fz72lOr8D8reFerunUyGQN7f4LTP"

